[arch_servers]
# Arch Linux servers
# arch1 ansible_host=192.168.1.40 ansible_user=admin
# arch2 ansible_host=192.168.1.41 ansible_user=admin

[arch_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
package_manager=pacman

