[rhel_servers]
# RHEL/CentOS/Rocky/AlmaLinux servers
# rhel1 ansible_host=192.168.1.20 ansible_user=admin
# rhel2 ansible_host=192.168.1.21 ansible_user=admin

[rhel_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
package_manager=yum

